#ifndef usb_audio_defines_h_
#define usb_audio_defines_h_

#ifndef AUDIO_SUBSLOT_SIZE
#define AUDIO_SUBSLOT_SIZE 4
#endif

#define AUDIO_BITRESOLUTION (8 * AUDIO_SUBSLOT_SIZE)

#define CEIL_DIV(x, y) (((x) + (y) - 1) / (y))

#define USB_AUDIO_CHANNEL_FL  (1 << 0)
#define USB_AUDIO_CHANNEL_FR  (1 << 1)
#define USB_AUDIO_CHANNEL_FC  (1 << 2)
#define USB_AUDIO_CHANNEL_LFE (1 << 3)
#define USB_AUDIO_CHANNEL_RL  (1 << 4)
#define USB_AUDIO_CHANNEL_RR  (1 << 5)
#define USB_AUDIO_CHANNEL_FLC (1 << 6)
#define USB_AUDIO_CHANNEL_FRC (1 << 7)
#define USB_AUDIO_CHANNEL_RC  (1 << 8)
#define USB_AUDIO_CHANNEL_SL  (1 << 9)
#define USB_AUDIO_CHANNEL_SR  (1 << 10)

#define MS_PER_SEC 1000
#define MAX_SAMPLES_PER_MS CEIL_DIV(AUDIO_SAMPLE_RATE_I, MS_PER_SEC)
#define RX_TX_ADD_SAMPLES 1

#if defined(AUDIO_USB_CHANNEL_COUNT)
  #define USB_AUDIO_NO_CHANNELS_480 (((AUDIO_USB_CHANNEL_COUNT) < 2) ? 2 : ((AUDIO_USB_CHANNEL_COUNT) & ~1))
#else
  #define USB_AUDIO_NO_CHANNELS_480 8
#endif

#if USB_AUDIO_NO_CHANNELS_480 == 2
  #define CHANNEL_CONFIG_480 (USB_AUDIO_CHANNEL_FL | USB_AUDIO_CHANNEL_FR)
#elif USB_AUDIO_NO_CHANNELS_480 == 4
  #define CHANNEL_CONFIG_480 (USB_AUDIO_CHANNEL_FL | USB_AUDIO_CHANNEL_FR | USB_AUDIO_CHANNEL_RL | USB_AUDIO_CHANNEL_RR)
#elif USB_AUDIO_NO_CHANNELS_480 == 6
  #define CHANNEL_CONFIG_480 (USB_AUDIO_CHANNEL_FL | USB_AUDIO_CHANNEL_FR | USB_AUDIO_CHANNEL_FC | USB_AUDIO_CHANNEL_LFE | USB_AUDIO_CHANNEL_SL | USB_AUDIO_CHANNEL_SR)
#elif USB_AUDIO_NO_CHANNELS_480 == 8
  #define CHANNEL_CONFIG_480 (USB_AUDIO_CHANNEL_FL | USB_AUDIO_CHANNEL_FR | USB_AUDIO_CHANNEL_FC | USB_AUDIO_CHANNEL_LFE | USB_AUDIO_CHANNEL_RL | USB_AUDIO_CHANNEL_RR | USB_AUDIO_CHANNEL_SL | USB_AUDIO_CHANNEL_SR)
#endif

#define AUDIO_NUM_SUBFRAMES_PER_POLLING_480 (1 << (AUDIO_POLLING_INTERVAL_480 - 1))
#define AUDIO_RX_TX_SIZE_SAMPLES_480 (CEIL_DIV(AUDIO_SAMPLE_RATE_I, (8000 / AUDIO_NUM_SUBFRAMES_PER_POLLING_480)) + RX_TX_ADD_SAMPLES)
#define AUDIO_RX_SIZE_480 (AUDIO_RX_TX_SIZE_SAMPLES_480 * USB_AUDIO_NO_CHANNELS_480 * AUDIO_SUBSLOT_SIZE)
#define AUDIO_TX_SIZE_480 AUDIO_RX_SIZE_480

#if defined(AUDIO_USB_CHANNEL_COUNT)
  #define USB_AUDIO_NO_CHANNELS_12 (((AUDIO_USB_CHANNEL_COUNT) < 2) ? 2 : ((AUDIO_USB_CHANNEL_COUNT) & ~1))
#else
  #define USB_AUDIO_NO_CHANNELS_12 2
#endif

#if USB_AUDIO_NO_CHANNELS_12 == 2
  #define CHANNEL_CONFIG_12 (USB_AUDIO_CHANNEL_FL | USB_AUDIO_CHANNEL_FR)
#elif USB_AUDIO_NO_CHANNELS_12 == 4
  #define CHANNEL_CONFIG_12 (USB_AUDIO_CHANNEL_FL | USB_AUDIO_CHANNEL_FR | USB_AUDIO_CHANNEL_RL | USB_AUDIO_CHANNEL_RR)
#elif USB_AUDIO_NO_CHANNELS_12 == 6
  #define CHANNEL_CONFIG_12 (USB_AUDIO_CHANNEL_FL | USB_AUDIO_CHANNEL_FR | USB_AUDIO_CHANNEL_FC | USB_AUDIO_CHANNEL_LFE | USB_AUDIO_CHANNEL_SL | USB_AUDIO_CHANNEL_SR)
#elif USB_AUDIO_NO_CHANNELS_12 == 8
  #define CHANNEL_CONFIG_12 (USB_AUDIO_CHANNEL_FL | USB_AUDIO_CHANNEL_FR | USB_AUDIO_CHANNEL_FC | USB_AUDIO_CHANNEL_LFE | USB_AUDIO_CHANNEL_RL | USB_AUDIO_CHANNEL_RR | USB_AUDIO_CHANNEL_SL | USB_AUDIO_CHANNEL_SR)
#endif

#define AUDIO_NUM_SUBFRAMES_PER_POLLING_12 8
#define AUDIO_RX_TX_SIZE_SAMPLES_12 (MAX_SAMPLES_PER_MS + RX_TX_ADD_SAMPLES)
#define AUDIO_RX_SIZE_12 (AUDIO_RX_TX_SIZE_SAMPLES_12 * USB_AUDIO_NO_CHANNELS_12 * AUDIO_SUBSLOT_SIZE)
#define AUDIO_TX_SIZE_12 AUDIO_RX_SIZE_12

#if (USB_AUDIO_NO_CHANNELS_12) < (USB_AUDIO_NO_CHANNELS_480)
  #define USB_AUDIO_MAX_NO_CHANNELS USB_AUDIO_NO_CHANNELS_480
#else
  #define USB_AUDIO_MAX_NO_CHANNELS USB_AUDIO_NO_CHANNELS_12
#endif

#endif
